compile_commands: ${DYLINX_HOME}/sample/access_counting/compile_commands.json
output_directory: ${DYLINX_HOME}/sample/access_counting
instructions:
  - build: "make sample"
  - clean: "make clean"
  - execute: "./bin/sample"
